import Navbar from '@/components/navbar/navbar'
import './globals.css'
import VerticalScrollBar from '@/components/verticalScrollBar'
import { rubik, nunito } from '@/app/fonts'
import VerticalNavbar from '@/components/navbar/vertival-navbar'
import { Toaster } from '@/components/ui/toaster'

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <head>
        <meta charSet='UTF-8' />
        <meta name="theme-color" content="#000" />
      </head>
      <body className={`${rubik.variable} ${nunito.variable} bg-black`}>
        <Navbar />
        <VerticalNavbar />
        <VerticalScrollBar />
        <Toaster />
        {children}
      </body>
    </html>
  )
}
