import Navbar from '@/components/navbar/navbar'
import './globals.css'
import VerticalScrollBar from '@/components/verticalScrollBar'
import { rubik, nunito } from '@/app/fonts'

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <head>
        <meta charSet='UTF-8' />
      </head>
      <body className={`${rubik.variable} ${nunito.variable} bg-black`}>
        <Navbar />
        <VerticalScrollBar />
        {children}
      </body>
    </html>
  )
}
